
# Disable old lighting because, just no
oldLighting = false

# We need to separate vanilla ao in order to make it only show in shadows
separateAo = true


# Shader settings: Main Menu
screen = [Shadows] [Material] [SSRT]

# Shader settings: Sub Menu 1
screen.Shadows = shadowMapResolution
screen.Material = noPBR_RP
screen.SSRT = doSSRT blurSSRT doTemporal MULTI_BOUNCE russianRoulette

# Slider settings
sliders = shadowMapResolution